name: Generate & Deploy Sitemap

on:
  schedule:
    - cron: '0 6 * * *'  # 毎朝6時（日本時間15時）に実行
  workflow_dispatch:

jobs:
  sitemap:
    runs-on: ubuntu-latest


    services:
      postgres:
        image: postgres:17  
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres:password@localhost:5432/sitemap_db
          POSTGRES_DB: sitemap_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Set up database
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/sitemap_db
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Generate sitemap
        run: bundle exec rake sitemap:refresh

      - name: Commit sitemap
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add public/sitemap.xml.gz || echo "No sitemap found"
          git commit -m "Auto update sitemap [skip ci]" || echo "No changes to commit"
          git push origin main

      - name: Trigger Render deploy
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK_URL"
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
